app = 'piyrox'
primary_region = 'jnb'
kill_signal = "SIGTERM"
kill_timeout = "10s"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "35s"
  interval = "30s"
  method = "GET"
  path = "/api/v1"
  timeout = "5s"
