import type { Metadata } from 'next';
import { ShoppingCart, Search, CreditCard, Package, CheckCircle2 } from 'lucide-react';
import { DocHeader, DocSection, Steps, Callout, FeatureGrid, RelatedLinks, DocShell } from '../components/doc-ui';

export const metadata: Metadata = {
  title: 'How to Buy — Velxo Documentation',
  description:
    'Step-by-step guide to buying game accounts, items and top-ups on Velxo: browse, checkout, escrow, pay via payment link, receive delivery, release escrow.',
  alternates: { canonical: 'https://market.velxo.shop/docs/buy' },
};

export default function DocsBuy() {
  return (
    <DocShell>
      <DocHeader
        icon={<ShoppingCart className="w-6 h-6" />}
        title="How to Buy"
        description="Buying on Velxo is built around one idea: you only pay the seller once you've confirmed you received what you paid for. Here's the full journey from browsing to a completed, protected trade."
      />

      <DocSection title="The buyer journey at a glance">
        <Steps
          items={[
            { title: 'Browse listings', body: 'Explore verified listings by game, category (accounts, top-ups, coins, boosting) or price.' },
            { title: 'Start checkout', body: 'Open a listing and begin checkout. Your order is created and escrow is initiated.' },
            { title: 'Pay via payment link', body: 'Complete payment through the secure payment link (cards, bank transfer, mobile money).' },
            { title: 'Seller delivers', body: 'The seller shares account credentials or fulfills the top-up / service.' },
            { title: 'Receive & verify', body: 'Log in or confirm the delivery works as described.' },
            { title: 'Release escrow', body: 'Confirm satisfaction and the funds are released to the seller.' },
          ]}
        />
      </DocSection>

      <DocSection title="1. Browse & choose a listing">
        <p>
          Use the search bar and category filters to narrow results. Always check the seller&apos;s{' '}
          <span className="text-white font-semibold">Verified</span> badge, rating, and number of
          completed sales before purchasing. Verified sellers have passed KYC and are generally
          safer to trade with.
        </p>
        <Callout type="tip" title="Look for the green badge">
          A verified seller shows a blue shield badge on their profile and listings. Prefer verified
          sellers, especially for high-value accounts.
        </Callout>
      </DocSection>

      <DocSection title="2. Checkout & escrow">
        <p>
          When you start checkout, Velxo creates an order and locks the amount in escrow. The money
          does not go to the seller yet — it is held safely until you release it. You&apos;ll see the
          order status change to <span className="text-white font-semibold">Awaiting Payment</span>.
        </p>
      </DocSection>

      <DocSection title="3. Pay via payment link">
        <p>
          You&apos;ll receive a secure payment link generated by our payment partners (Paystack /
          Flutterwave). Pay using your preferred local method. Once payment is confirmed, the order
          moves to <span className="text-white font-semibold">Paid — awaiting delivery</span> and the
          seller is notified to deliver.
        </p>
        <Callout type="warning" title="Never pay outside Velxo">
          Always pay through the in-app payment link. Payments sent directly to a seller via chat or
          external apps are NOT covered by escrow and cannot be recovered.
        </Callout>
      </DocSection>

      <DocSection title="4. Receive delivery">
        <p>
          The seller delivers in one of two ways: credentials shared through the order chat, or a
          direct top-up/boost applied to your account. As soon as you receive the details, log in and
          verify everything matches the listing description (rank, skins, currency, bindings, etc.).
        </p>
        <FeatureGrid
          items={[
            { icon: <Package className="w-5 h-5" />, title: 'Accounts', body: 'Verify login works, email is changeable, and details match the listing.' },
            { icon: <CreditCard className="w-5 h-5" />, title: 'Top-ups & coins', body: 'Confirm the balance or currency landed in your game account.' },
            { icon: <CheckCircle2 className="w-5 h-5" />, title: 'Boosting', body: 'Track progress in your order chat until the service is complete.' },
          ]}
        />
      </DocSection>

      <DocSection title="5. Release escrow">
        <p>
          Happy with the delivery? Release the escrow from your order page. The funds are transferred
          to the seller and the trade is complete. If something is wrong, open a dispute instead of
          releasing — see <span className="text-white font-semibold">Disputes &amp; Support</span>.
        </p>
        <Callout type="info" title="Auto-release">
          If you don&apos;t act within the review window, escrow may auto-release to protect sellers
          from indefinite holds. Always review promptly.
        </Callout>
      </DocSection>

      <RelatedLinks links={[{ label: 'How Escrow Works', href: '/docs/escrow' }, { label: 'Payments & Wallets', href: '/docs/payments' }, { label: 'Disputes & Support', href: '/docs/disputes' }]} />
    </DocShell>
  );
}
